In [2]:
import tensorflow as tf
import numpy as np

In [49]:
with tf.Session() as sess:
    x = tf.placeholder(tf.float32, shape=(None, 2), name='x')
    y_2 = tf.reduce_sum(tf.pow(x, 2), axis=1)
    y_3 = tf.reduce_sum(tf.pow(x, 3), axis=1)
    
    y = tf.stack([y_2,y_3], axis=1)
    x_input = np.array([3,2,4,5,7,6]).reshape(-1,2)

    print('------')
    res_y_2, res_y_3 = sess.run([y_2,y_3], feed_dict={x: x_input});
    print(res_y_2)
    print(res_y_3)
    print('------')
    max_pred = tf.reduce_max(y, axis=1)
    gradient = tf.gradients(y, x)
    grad_max_pred = tf.gradients(max_pred, x)
    
    res, grad_res, max_pred_res, grad_max_pred = sess.run([y, gradient, max_pred, grad_max_pred], feed_dict={x: x_input})
    
    
    print(x_input)
    print(res.shape)
    print(res)
    print('----- grad -----')
    print(grad_res)
    print('---- max_pred ----')
    print(max_pred_res)
    print('---- grad max pred')
    print(grad_max_pred)
#     print('x=%f , y=%f' %(x_input, res))

------
[ 13.  41.  85.]
[  35.  189.  559.]
------
[[3 2]
 [4 5]
 [7 6]]
(3, 2)
[[  13.   35.]
 [  41.  189.]
 [  85.  559.]]
----- grad -----
[array([[  33.,   16.],
       [  56.,   85.],
       [ 161.,  120.]], dtype=float32)]
---- max_pred ----
[  35.  189.  559.]
---- grad max pred
[array([[  27.,   12.],
       [  48.,   75.],
       [ 147.,  108.]], dtype=float32)]


In [21]:
grad_func = lambda x: 2*x + 3*(x**2)

In [28]:
grad_func(7)

161